# Use an official Node runtime as a parent image
FROM node:14

# Set the working directory to /frontend
WORKDIR /yoga-frontend

# Copy the current directory contents into the container at /frontend
COPY ./yoga-frontend /yoga-frontend

# Install any needed packages specified in package.json
RUN npm install

# Make port 3000 available to the world outside this container
EXPOSE 3000

# Define the command to run your application
CMD ["npm", "start"]
